# Setup
title:               'Erick Matsen'
tagline:             'Field Notes'
description:         'Thoughts with no other home.'
url:                 https://matsen.github.io/

# About/contact
author:
  name: Erick Matsen
  url: http://matsen.group/
  email: matsen@fredhutch.org
