# Setup
title:               'Erick Matsen'
tagline:             'Field Notes'
url:                 https://erick.matsen.org/

# About/contact
author:
  name: Erick Matsen
  url: http://matsen.group/
  email: matsen@fredhutch.org

plugins:
  - jekyll-feed
